FORMAT: 1A
HOST: http://www.google.com

# Superbowl IDB API
a website with a database about Superbowls past

## Superbowl Games [/games]
### List all Games [GET]
+ Response 200 (application/json)
    
        [{
            "winning_team" : "Seahawks",
            "losing_team" : "Broncos",
            "venue" : "MetLife Stadium",
            "score" : "43-8",
            "game_number" : "XLVIII",
            "attendance" : "82529",
            "game_day" : "2014-02-02" 
        }]
