FORMAT: 1A
HOST: http://www.google.com

# IDB
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Superbowl Games [/games]
### List all Games [GET]
+ Response 200 (application/json)

