FORMAT: 1A
HOST: http://www.google.com

# Superbowl IDB API
a website with a database about Superbowls past

# HTTP status codes as stated below are expected to be followed:

200 `OK` - the request was successful (some API calls may return 201 instead).
201 `Created` - the request was successful and a resource was created.
204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
400 `Bad Request` - the request could not be understood or was missing required parameters.
401 `Unauthorized` - authentication failed or user doesn't have permissions for requested operation.
403 `Forbidden` - access denied.
404 `Not Found` - resource was not found
405 `Method Not Allowed` - requested method is not supported for resource.

## Superbowl Games [/api/games]

### List all Games [GET]
+ Response 200 (application/json)

        [
                {
                    "home_team" : [1],
                    "away_team" : [1],
                    "home_score" : 48,
                    "away_score" : 3,
                    "venue" : [0],
                    "game_day" : "2014-2-14",
                    "game_number" : "XLVIII"
                }
        ]

### Add info about a single game [POST]
+ Request (application/json)

        {
            "home_team" : [1],
            "away_team" : [1],
            "home_score" : 48,
            "away_score" : 3,
            "venue" : [0],
            "game_day" : "2014-2-14",
            "game_number" : "XLVIII"
        }
        
+ Response 201 (application/json)

        {"id" : 1}
        
## Superbowl Teams [/api/teams]

### List all Teams [GET]
+ Response 200 (application/json)

        [
                {
                    "team_name" : "Seahawks",
                    "team_city" : "Seattle",
                    "owner" : "Paul Allen"
                }
        ]

### Add info about a single Team [POST]
+ Request (application/json)

        {
            "team_name" : "Seahawks",
            "team_city" : "Seattle",
            "owner" : "Paul Allen"
        }
        
+ Response 201 (application/json)
    
        {"id" : 1}

## Superbowl Players [/api/players]

### List all Players [GET]
+ Response 200 (application/json)

        [
                {
                    "first_name" : "Peyton",
                    "last_name" : "Manning",
                    "birth_date" : "1976-03-24",
                    "birth_town" : "New Orleans, LA",
                    "high_school" : "New Orleans Newman",
                    "college" : "University of Tennessee"
                }
        ]

### Add info about a single player [POST]
+ Request (application/json)

        {
            "first_name" : "Peyton",
            "last_name" : "Manning",
            "birth_date" : "1976-03-24",
            "birth_town" : "New Orleans, LA",
            "high_school" : "New Orleans Newman",
            "college" : "University of Tennessee"
        }
        
+ Response 201 (application/json)

        {"id" : 1}

## A Specific Game [/api/games/{id}]

### List info about a single game [GET]
+ Response 200 (application/json)

        {
            "home_team" : [1],
            "away_team" : [1],
            "home_score" : 48,
            "away_score" : 3,
            "venue" : [0],
            "game_day" : "2014-2-14",
            "game_number" : "XLVIII"
        }

### Update info about a single game [PUT]
+ Request (application/json)

        {
            "home_team" : [1],
            "away_team" : [1],
            "home_score" : 48,
            "away_score" : 3,
            "venue" : [0],
            "game_day" : "2014-2-14",
            "game_number" : "XLX"
        }
+ Response 204

### Remove info about a single game [DELETE]
+ Response 204

## A Specific Team [/api/teams/{id}]

### List info about a single team [GET]
+ Response 200 (application/json)

        {
            "team_name" : "Seahawks",
            "team_city" : "Seattle",
            "owner" : "Paul Allen"
        }

### Update info about a single team [PUT]
+ Request (application/json)

        {
            "team_name" : "Seahawks",
            "team_city" : "Seattle",
            "owner" : "Paul Allen"
        }
+ Response 204

### Remove info about a single team [DELETE]
+ Response 204

## A Specific Player [/api/players/{id}]

### List info about a single player [GET]
+ Response 200 (application/json)

        {
            "first_name" : "Peyton",
            "last_name" : "Manning",
            "birth_date" : "1976-03-24",
            "birth_town" : "New Orleans, LA",
            "high_school" : "New Orleans Newman",
            "college" : "University of Tennessee"
        }

### Update info about a single player [PUT]
+ Request (application/json)
    
        {
            "first_name" : "Peyton",
            "last_name" : "Manning",
            "birth_date" : "1976-03-24",
            "birth_town" : "New Orleans, LA",
            "high_school" : "New Orleans Newman",
            "college" : "The University of Tennessee"
        }

+ Response 204

### Remove info about a single player [DELETE]
+ Response 204

